#!/usr/bin/env python3
"""
notes.py — scaffolding + index generation for the AI course notes site.

Usage
  python3 tools/notes.py new-course <slug> --title "..." [--code CS229] [--org "Stanford Online"]
                                            [--desc "..."] [--source URL] [--tags "a, b"]
  python3 tools/notes.py new-lecture <course-slug> "<Lecture title>" [--number N] [--slug s]
                                            [--summary "..."] [--tags "a, b"] [--date YYYY-MM-DD]
                                            [--source URL]
  python3 tools/notes.py reindex          # rebuild index.html, course pages, prev/next + sidebar nav
  python3 tools/notes.py list

Everything is plain static HTML — reindex only rewrites generated regions, never your notes.
"""
import argparse, datetime, html, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COURSES = os.path.join(ROOT, "courses")
TEMPLATES = os.path.join(ROOT, "templates")

GEN = "<!-- Generated by tools/notes.py reindex — edit course.json / the lecture files instead. -->"


# ---------------------------------------------------------------- helpers
def e(s):
    return html.escape(str(s or ""), quote=True)


def slugify(s):
    s = re.sub(r"[^\w\s-]", "", str(s).lower()).strip()
    s = re.sub(r"[\s_]+", "-", s)
    return re.sub(r"-+", "-", s) or "untitled"


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def write(p, s):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


def replace_region(text, name, new_inner):
    start, end = f"<!-- {name}:START -->", f"<!-- {name}:END -->"
    pat = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
    block = start + new_inner + end
    if pat.search(text):
        return pat.sub(lambda _: block, text, count=1)
    return text


def meta_of(doc, name):
    m = re.search(r'<meta\s+name="%s"\s+content="(.*?)"' % re.escape(name), doc, re.S)
    return html.unescape(m.group(1)) if m else ""


# ---------------------------------------------------------------- model
def load_courses():
    out = []
    if not os.path.isdir(COURSES):
        return out
    for slug in sorted(os.listdir(COURSES)):
        d = os.path.join(COURSES, slug)
        cfg = os.path.join(d, "course.json")
        if not os.path.isdir(d) or not os.path.exists(cfg):
            continue
        c = json.loads(read(cfg))
        c["slug"] = slug
        c["dir"] = d
        c["lectures"] = load_lectures(d)
        out.append(c)
    out.sort(key=lambda c: (c.get("order", 999), c.get("title", "")))
    return out


def load_lectures(d):
    lects = []
    for fn in sorted(os.listdir(d)):
        if not fn.endswith(".html") or fn == "index.html":
            continue
        doc = read(os.path.join(d, fn))
        t = re.search(r"<title>(.*?)</title>", doc, re.S)
        title = html.unescape(t.group(1)).split("·")[0].strip() if t else fn
        num = meta_of(doc, "note:number") or (re.match(r"(\d+)", fn).group(1) if re.match(r"\d", fn) else "")
        lects.append({
            "file": fn,
            "title": title,
            "number": num,
            "date": meta_of(doc, "note:date"),
            "tags": meta_of(doc, "note:tags"),
            "summary": meta_of(doc, "description"),
        })
    lects.sort(key=lambda l: (l["file"],))
    return lects


# ---------------------------------------------------------------- page shells
def shell(title, root, body, description=""):
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(title)}</title>
<meta name="description" content="{e(description)}">
<script>(function(){{try{{var t=localStorage.getItem('notes-theme');if(t)document.documentElement.dataset.theme=t}}catch(e){{}}}})();</script>
<link rel="stylesheet" href="{root}assets/notes.css">
<script defer src="{root}assets/notes.js"></script>
</head>
<body>
{GEN}
{body}
</body>
</html>
"""


def course_card(c):
    n = len(c["lectures"])
    tags = "".join(f'<span class="chip">{e(t)}</span>' for t in (c.get("tags") or [])[:3])
    sub = " · ".join(x for x in [c.get("org"), c.get("code")] if x)
    search = " ".join([c.get("title", ""), c.get("code", ""), c.get("org", ""), c.get("description", "")]
                      + list(c.get("tags") or []))
    return f"""      <li data-searchable="{e(search)}">
        <a class="card" href="courses/{c['slug']}/index.html">
          <span class="card__code">{e(sub)}</span>
          <h2 class="card__title">{e(c.get('title'))}</h2>
          <p class="card__desc">{e(c.get('description'))}</p>
          <span class="card__foot"><span>{n} lecture{'s' if n != 1 else ''}</span>{tags}</span>
        </a>
      </li>"""


def build_root_index(courses):
    total = sum(len(c["lectures"]) for c in courses)
    cards = "\n".join(course_card(c) for c in courses)
    if not courses:
        cards_block = ('<div class="empty-state">No courses yet. Create one with '
                       '<code>python3 tools/notes.py new-course cme296 --title "Diffusion &amp; Large Vision Models"</code></div>')
    else:
        cards_block = f'<ul class="cards">\n{cards}\n    </ul>'
    body = f"""<header class="topbar">
  <a class="topbar__brand" href="index.html">AI Notes<span class="dot">.</span></a>
  <span class="topbar__spacer"></span>
  <button class="iconbtn" data-theme-toggle aria-label="Toggle theme">☾</button>
</header>

<div class="page">
  <div class="page-head">
    <p class="kicker">Learning notes</p>
    <h1>AI course notes</h1>
    <p>My notes from online AI &amp; machine-learning courses — written up lecture by lecture,
       kept as plain HTML so they open anywhere and never rot.</p>
  </div>

  <div class="toolbar">
    <label class="search">
      <span aria-hidden="true">⌕</span>
      <input id="filter" type="search" placeholder="Filter courses…" autocomplete="off">
      <kbd>/</kbd>
    </label>
    <span class="count" id="filterCount">{len(courses)} total</span>
    <span class="count">{total} lecture notes</span>
  </div>

  {cards_block}
</div>

<footer class="site-foot">Static HTML · press <kbd>t</kbd> to switch theme, <kbd>/</kbd> to filter · <a href="templates/components.html">note components</a> · built with <code>tools/notes.py</code></footer>"""
    return shell("AI course notes", "", body, "Personal learning notes from online AI courses.")


def build_course_index(c):
    rows = []
    for l in c["lectures"]:
        num = e(l["number"] or "•")
        sub = f'<span class="sub">{e(l["summary"])}</span>' if l["summary"] else ""
        tag = f'<span class="tag">{e(l["date"])}</span>' if l["date"] else ""
        rows.append(f"""      <li data-searchable="{e(l['title'] + ' ' + l['summary'] + ' ' + l['tags'])}">
        <a href="{e(l['file'])}">
          <span class="num">{num}</span>
          <span class="grow"><span class="ttl">{e(l['title'])}</span>{sub}</span>
          {tag}
        </a>
      </li>""")
    if rows:
        listing = '<ul class="lectures">\n' + "\n".join(rows) + "\n    </ul>"
    else:
        listing = ('<div class="empty-state">No lectures yet. Add one with<br>'
                   f'<code>python3 tools/notes.py new-lecture {e(c["slug"])} "Lecture title"</code></div>')
    meta_bits = [x for x in [c.get("org"), c.get("code"), f'{len(c["lectures"])} lectures'] if x]
    src = (f'<li><a class="chip chip--accent" href="{e(c["source"])}" target="_blank" rel="noopener">Course page ↗</a></li>'
           if c.get("source") else "")
    tags = "".join(f'<li class="chip">{e(t)}</li>' for t in (c.get("tags") or []))
    body = f"""<header class="topbar">
  <a class="topbar__brand" href="../../index.html">AI Notes<span class="dot">.</span></a>
  <nav class="crumbs" aria-label="Breadcrumb">
    <span class="sep">/</span><span class="current">{e(c.get('title'))}</span>
  </nav>
  <span class="topbar__spacer"></span>
  <button class="iconbtn" data-theme-toggle aria-label="Toggle theme">☾</button>
</header>

<div class="page">
  <div class="page-head">
    <p class="kicker">{e(' · '.join(meta_bits))}</p>
    <h1>{e(c.get('title'))}</h1>
    <p>{e(c.get('description'))}</p>
    <ul class="chips">{tags}{src}</ul>
  </div>

  <div class="toolbar">
    <label class="search">
      <span aria-hidden="true">⌕</span>
      <input id="filter" type="search" placeholder="Filter lectures…" autocomplete="off">
      <kbd>/</kbd>
    </label>
    <span class="count" id="filterCount"></span>
  </div>

  {listing}
</div>

<footer class="site-foot"><a href="../../index.html">← All courses</a></footer>"""
    return shell(f"{c.get('title')} · AI course notes", "../../", body, c.get("description", ""))


# ---------------------------------------------------------------- lecture nav regions
def pager_html(prev, nxt):
    if prev:
        p = f'<a class="prev" href="{e(prev["file"])}"><span class="dir">← Previous</span><span class="ttl">{e(prev["title"])}</span></a>'
    else:
        p = '<a class="prev empty"><span class="dir">Start of course</span><span class="ttl">—</span></a>'
    if nxt:
        n = f'<a class="next" href="{e(nxt["file"])}"><span class="dir">Next →</span><span class="ttl">{e(nxt["title"])}</span></a>'
    else:
        n = '<a class="next empty"><span class="dir">End of course</span><span class="ttl">—</span></a>'
    return f'\n    <nav class="pager">\n      {p}\n      {n}\n    </nav>\n    '


def siblings_html(lectures, current):
    items = []
    for l in lectures:
        cls = ' class="is-active"' if l["file"] == current else ""
        num = f'{e(l["number"])} · ' if l["number"] else ""
        items.append(f'<li><a href="{e(l["file"])}"{cls}>{num}{e(l["title"])}</a></li>')
    return ('\n    <hr>\n    <p class="sidebar__label">Lectures</p>\n'
            '    <nav class="toc">\n      <ul>\n        '
            + "\n        ".join(items) + "\n      </ul>\n    </nav>\n  ")


def update_lectures(c):
    ls = c["lectures"]
    for i, l in enumerate(ls):
        path = os.path.join(c["dir"], l["file"])
        doc = read(path)
        doc = replace_region(doc, "PAGER", pager_html(ls[i - 1] if i else None, ls[i + 1] if i + 1 < len(ls) else None))
        doc = replace_region(doc, "SIBLINGS", siblings_html(ls, l["file"]))
        doc = replace_region(doc, "CRUMB", f'<a href="index.html">{e(c.get("title"))}</a>')
        write(path, doc)


# ---------------------------------------------------------------- commands
def cmd_reindex(_):
    courses = load_courses()
    write(os.path.join(ROOT, "index.html"), build_root_index(courses))
    for c in courses:
        write(os.path.join(c["dir"], "index.html"), build_course_index(c))
        update_lectures(c)
        print(f"  {c['slug']}: {len(c['lectures'])} lectures")
    print(f"reindexed {len(courses)} course(s) → index.html")


def cmd_new_course(a):
    slug = slugify(a.slug)
    d = os.path.join(COURSES, slug)
    cfg = os.path.join(d, "course.json")
    if os.path.exists(cfg):
        sys.exit(f"course.json already exists: {cfg}")
    data = {
        "title": a.title or slug,
        "code": a.code or "",
        "org": a.org or "",
        "description": a.desc or "",
        "source": a.source or "",
        "tags": [t.strip() for t in (a.tags or "").split(",") if t.strip()],
        "order": a.order,
    }
    write(cfg, json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    print(f"created {os.path.relpath(cfg, ROOT)}")
    cmd_reindex(a)


def cmd_new_lecture(a):
    d = os.path.join(COURSES, a.course)
    if not os.path.exists(os.path.join(d, "course.json")):
        sys.exit(f"no such course: {a.course} (run new-course first)")
    c = json.loads(read(os.path.join(d, "course.json")))
    existing = load_lectures(d)
    number = a.number if a.number is not None else len(existing) + 1
    fname = f"{number:02d}-{slugify(a.slug or a.title)}.html"
    path = os.path.join(d, fname)
    if os.path.exists(path):
        sys.exit(f"already exists: {path}")
    doc = read(os.path.join(TEMPLATES, "lecture.html"))
    for k, v in {
        "{{ROOT}}": "../../",
        "{{TITLE}}": e(a.title),
        "{{COURSE_TITLE}}": e(c.get("title", a.course)),
        "{{NUMBER}}": f"{number:02d}",
        "{{DATE}}": a.date or datetime.date.today().isoformat(),
        "{{SUMMARY}}": e(a.summary or "One-line summary of this lecture."),
        "{{TAGS}}": e(a.tags or (c.get("tags") or [""])[0]),
        "{{SOURCE_URL}}": e(a.source or c.get("source") or "#"),
    }.items():
        doc = doc.replace(k, v)
    write(path, doc)
    print(f"created {os.path.relpath(path, ROOT)}")
    cmd_reindex(a)


def cmd_list(_):
    for c in load_courses():
        print(f"{c['slug']:24} {c.get('title','')}  ({len(c['lectures'])} lectures)")
        for l in c["lectures"]:
            print(f"    {l['number'] or '--':>3}  {l['file']:<38} {l['title']}")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    nc = sub.add_parser("new-course")
    nc.add_argument("slug")
    nc.add_argument("--title"); nc.add_argument("--code"); nc.add_argument("--org")
    nc.add_argument("--desc"); nc.add_argument("--source"); nc.add_argument("--tags")
    nc.add_argument("--order", type=int, default=100)
    nc.set_defaults(func=cmd_new_course)

    nl = sub.add_parser("new-lecture")
    nl.add_argument("course"); nl.add_argument("title")
    nl.add_argument("--number", type=int); nl.add_argument("--slug")
    nl.add_argument("--summary"); nl.add_argument("--tags")
    nl.add_argument("--date"); nl.add_argument("--source")
    nl.set_defaults(func=cmd_new_lecture)

    sub.add_parser("reindex").set_defaults(func=cmd_reindex)
    sub.add_parser("list").set_defaults(func=cmd_list)

    a = p.parse_args()
    a.func(a)


if __name__ == "__main__":
    main()
